-- Insertion de recettes d'exemple simplifiées
INSERT INTO recipes (
  title, 
  slug, 
  description, 
  image, 
  images, 
  category, 
  prep_time, 
  servings, 
  is_vegetarian, 
  difficulty, 
  tags, 
  ingredients, 
  instructions, 
  nutrition_info, 
  is_premium, 
  is_published,
  published_at
) VALUES 
(
  'Smoothie Bowl Proteine aux Baies',
  'smoothie-bowl-proteine-baies',
  'Un smoothie bowl energisant et riche en proteines, parfait pour commencer la journee avec vitalite.',
  '/api/placeholder/400/300',
  '["/api/placeholder/400/300", "/api/placeholder/400/300"]',
  'breakfast',
  10,
  1,
  true,
  'easy',
  '["proteines", "antioxydants", "sans-gluten", "vegan"]',
  '["1 banane congelee", "100g de myrtilles", "1 cuillere a soupe de poudre de proteines vegetales", "150ml de lait damande", "1 cuillere a soupe de graines de chia", "Granola pour topping"]',
  '<h3>Preparation</h3><ol><li>Mixez la banane congelee avec les myrtilles et le lait damande</li><li>Ajoutez la poudre de proteines et mixez a nouveau</li><li>Versez dans un bol et decorez avec les graines de chia et le granola</li><li>Servez immediatement</li></ol>',
  '{"calories": 320, "protein": 18, "carbs": 45, "fat": 8}',
  false,
  true,
  NOW()
),
(
  'Salade de Quinoa aux Legumes Rotis',
  'salade-quinoa-legumes-rotis',
  'Une salade complete et nutritive avec du quinoa, des legumes rotis et une vinaigrette aux herbes.',
  '/api/placeholder/400/300',
  '["/api/placeholder/400/300", "/api/placeholder/400/300", "/api/placeholder/400/300"]',
  'lunch',
  25,
  2,
  true,
  'medium',
  '["proteines completes", "fibres", "sans-gluten", "vegan"]',
  '["150g de quinoa", "1 courgette", "1 aubergine", "1 poivron rouge", "2 tomates cerises", "1 oignon rouge", "2 cuilleres a soupe dhuile dolive", "Herbes de Provence", "Vinaigrette balsamique"]',
  '<h3>Preparation</h3><ol><li>Prechauffez le four a 200°C</li><li>Coupez les legumes en des et disposez-les sur une plaque</li><li>Arrosez dhuile dolive et dherbes, enfournez 20 min</li><li>Faites cuire le quinoa selon les instructions</li><li>Melangez le quinoa avec les legumes rotis</li><li>Arrosez de vinaigrette et servez</li></ol>',
  '{"calories": 280, "protein": 12, "carbs": 45, "fat": 6}',
  false,
  true,
  NOW()
),
(
  'Curry de Lentilles Corail aux Epinards',
  'curry-lentilles-corail-epinards',
  'Un curry vegetarien epice et reconfortant, riche en proteines et en fer.',
  '/api/placeholder/400/300',
  '["/api/placeholder/400/300", "/api/placeholder/400/300"]',
  'dinner',
  30,
  4,
  true,
  'medium',
  '["proteines", "fer", "epices", "vegan", "sans-gluten"]',
  '["200g de lentilles corail", "200g depinards frais", "1 oignon", "2 gousses dail", "1 boite de tomates concassees", "400ml de lait de coco", "2 cuilleres a cafe de curry", "1 cuillere a cafe de cumin", "1 cuillere a cafe de coriandre", "Riz basmati pour servir"]',
  '<h3>Preparation</h3><ol><li>Faites revenir loignon et lail dans une casserole</li><li>Ajoutez les epices et laissez dorer 2 min</li><li>Ajoutez les tomates et les lentilles, couvrez deau</li><li>Laissez mijoter 20 min jusqua ce que les lentilles soient tendres</li><li>Ajoutez le lait de coco et les epinards</li><li>Laissez cuire 5 min et servez avec le riz</li></ol>',
  '{"calories": 250, "protein": 15, "carbs": 35, "fat": 8}',
  true,
  true,
  NOW()
),
(
  'Energy Balls aux Dattes et Noix',
  'energy-balls-dattes-noix',
  'Des boules energetiques naturelles, parfaites comme collation pre ou post-entrainement.',
  '/api/placeholder/400/300',
  '["/api/placeholder/400/300"]',
  'snack',
  15,
  12,
  true,
  'easy',
  '["energie", "proteines", "sans-cuisson", "vegan", "sans-gluten"]',
  '["200g de dattes denoyautees", "100g de noix de cajou", "50g damandes", "2 cuilleres a soupe de cacao en poudre", "1 cuillere a soupe de graines de chia", "1 cuillere a soupe dhuile de coco", "Coco rapee pour rouler"]',
  '<h3>Preparation</h3><ol><li>Mixez les dattes avec les noix jusqua obtenir une pate</li><li>Ajoutez le cacao, les graines de chia et lhuile de coco</li><li>Mixez a nouveau jusqua ce que tout soit bien melange</li><li>Formez des boules de la taille dune noix</li><li>Roulez-les dans la coco rapee</li><li>Conservez au refrigerateur dans un contenant hermetique</li></ol>',
  '{"calories": 120, "protein": 4, "carbs": 18, "fat": 5}',
  false,
  true,
  NOW()
),
(
  'Buddha Bowl aux Legumes Croquants',
  'buddha-bowl-legumes-croquants',
  'Un bowl colore et equilibre avec des legumes croquants, des proteines et une sauce cremeuse.',
  '/api/placeholder/400/300',
  '["/api/placeholder/400/300", "/api/placeholder/400/300", "/api/placeholder/400/300"]',
  'lunch',
  20,
  1,
  true,
  'easy',
  '["equilibre", "couleurs", "crudites", "vegan", "sans-gluten"]',
  '["100g de quinoa cuit", "1/2 avocat", "1 carotte rapee", "1/2 concombre en rondelles", "50g de chou rouge rape", "2 cuilleres a soupe de pois chiches", "1 cuillere a soupe de graines de tournesol", "Sauce tahini", "Jus de citron", "Sel et poivre"]',
  '<h3>Preparation</h3><ol><li>Preparez le quinoa selon les instructions</li><li>Coupez lavocat en tranches et le concombre en rondelles</li><li>Rapez la carotte et le chou rouge</li><li>Disposez tous les ingredients dans un bol</li><li>Preparez la sauce en melangeant tahini, jus de citron, sel et poivre</li><li>Arrosez le bowl de sauce et servez</li></ol>',
  '{"calories": 380, "protein": 14, "carbs": 48, "fat": 16}',
  true,
  true,
  NOW()
),
(
  'Pancakes Proteines aux Flocons dAvoine',
  'pancakes-proteines-flocons-avoine',
  'Des pancakes moelleux et riches en proteines, parfaits pour un petit-dejeuner sportif.',
  '/api/placeholder/400/300',
  '["/api/placeholder/400/300", "/api/placeholder/400/300"]',
  'breakfast',
  20,
  2,
  true,
  'easy',
  '["proteines", "flocons davoine", "sans-gluten", "vegan"]',
  '["100g de flocons davoine", "1 banane mure", "2 cuilleres a soupe de poudre de proteines", "150ml de lait damande", "1 cuillere a cafe de levure chimique", "1 cuillere a soupe de sirop derable", "Huile de coco pour la cuisson"]',
  '<h3>Preparation</h3><ol><li>Mixez les flocons davoine en farine</li><li>Ecrasez la banane et melangez avec le lait damande</li><li>Ajoutez la farine davoine, les proteines et la levure</li><li>Melangez jusqua obtenir une pate homogene</li><li>Faites chauffer une poele avec un peu dhuile de coco</li><li>Versez des petites quantites de pate et faites cuire 2-3 min de chaque cote</li><li>Servez avec du sirop derable</li></ol>',
  '{"calories": 280, "protein": 20, "carbs": 35, "fat": 6}',
  false,
  true,
  NOW()
);

-- Verification des insertions
SELECT 
  title, 
  category, 
  difficulty, 
  is_premium, 
  is_published,
  jsonb_array_length(ingredients) as nb_ingredients,
  jsonb_array_length(tags) as nb_tags
FROM recipes 
ORDER BY created_at DESC;
