-- Insertion de recettes d'exemple pour tester l'interface
-- Basées sur les recettes végétariennes fournies

INSERT INTO recipes (
  title, 
  slug, 
  description, 
  image, 
  images, 
  category, 
  prep_time, 
  servings, 
  is_vegetarian, 
  difficulty, 
  tags, 
  ingredients, 
  instructions, 
  nutrition_info, 
  is_premium, 
  is_published,
  published_at
) VALUES 
(
  'Smoothie Bowl Protéiné aux Baies',
  'smoothie-bowl-proteine-baies',
  'Un smoothie bowl énergisant et riche en protéines, parfait pour commencer la journée avec vitalité.',
  '/api/placeholder/400/300',
  '["/api/placeholder/400/300", "/api/placeholder/400/300"]',
  'breakfast',
  10,
  1,
  true,
  'easy',
  '["protéines", "antioxydants", "sans-gluten", "vegan"]',
  '["1 banane congelée", "100g de myrtilles", "1 cuillère à soupe de poudre de protéines végétales", "150ml de lait d''amande", "1 cuillère à soupe de graines de chia", "Granola pour topping"]',
  '<h3>Préparation</h3><ol><li>Mixez la banane congelée avec les myrtilles et le lait d\'amande</li><li>Ajoutez la poudre de protéines et mixez à nouveau</li><li>Versez dans un bol et décorez avec les graines de chia et le granola</li><li>Servez immédiatement</li></ol>',
  '{"calories": 320, "protein": 18, "carbs": 45, "fat": 8}',
  false,
  true,
  NOW()
),
(
  'Salade de Quinoa aux Légumes Rôtis',
  'salade-quinoa-legumes-rotis',
  'Une salade complète et nutritive avec du quinoa, des légumes rôtis et une vinaigrette aux herbes.',
  '/api/placeholder/400/300',
  '["/api/placeholder/400/300", "/api/placeholder/400/300", "/api/placeholder/400/300"]',
  'lunch',
  25,
  2,
  true,
  'medium',
  '["protéines complètes", "fibres", "sans-gluten", "vegan"]',
  '["150g de quinoa", "1 courgette", "1 aubergine", "1 poivron rouge", "2 tomates cerises", "1 oignon rouge", "2 cuillères à soupe d\'huile d\'olive", "Herbes de Provence", "Vinaigrette balsamique"]',
  '<h3>Préparation</h3><ol><li>Préchauffez le four à 200°C</li><li>Coupez les légumes en dés et disposez-les sur une plaque</li><li>Arrosez d\'huile d\'olive et d\'herbes, enfournez 20 min</li><li>Faites cuire le quinoa selon les instructions</li><li>Mélangez le quinoa avec les légumes rôtis</li><li>Arrosez de vinaigrette et servez</li></ol>',
  '{"calories": 280, "protein": 12, "carbs": 45, "fat": 6}',
  false,
  true,
  NOW()
),
(
  'Curry de Lentilles Corail aux Épinards',
  'curry-lentilles-corail-epinards',
  'Un curry végétarien épicé et réconfortant, riche en protéines et en fer.',
  '/api/placeholder/400/300',
  '["/api/placeholder/400/300", "/api/placeholder/400/300"]',
  'dinner',
  30,
  4,
  true,
  'medium',
  '["protéines", "fer", "épices", "vegan", "sans-gluten"]',
  '["200g de lentilles corail", "200g d\'épinards frais", "1 oignon", "2 gousses d\'ail", "1 boîte de tomates concassées", "400ml de lait de coco", "2 cuillères à café de curry", "1 cuillère à café de cumin", "1 cuillère à café de coriandre", "Riz basmati pour servir"]',
  '<h3>Préparation</h3><ol><li>Faites revenir l\'oignon et l\'ail dans une casserole</li><li>Ajoutez les épices et laissez dorer 2 min</li><li>Ajoutez les tomates et les lentilles, couvrez d\'eau</li><li>Laissez mijoter 20 min jusqu\'à ce que les lentilles soient tendres</li><li>Ajoutez le lait de coco et les épinards</li><li>Laissez cuire 5 min et servez avec le riz</li></ol>',
  '{"calories": 250, "protein": 15, "carbs": 35, "fat": 8}',
  true,
  true,
  NOW()
),
(
  'Energy Balls aux Dattes et Noix',
  'energy-balls-dattes-noix',
  'Des boules énergétiques naturelles, parfaites comme collation pré ou post-entraînement.',
  '/api/placeholder/400/300',
  '["/api/placeholder/400/300"]',
  'snack',
  15,
  12,
  true,
  'easy',
  '["énergie", "protéines", "sans-cuisson", "vegan", "sans-gluten"]',
  '["200g de dattes dénoyautées", "100g de noix de cajou", "50g d\'amandes", "2 cuillères à soupe de cacao en poudre", "1 cuillère à soupe de graines de chia", "1 cuillère à soupe d\'huile de coco", "Coco râpée pour rouler"]',
  '<h3>Préparation</h3><ol><li>Mixez les dattes avec les noix jusqu\'à obtenir une pâte</li><li>Ajoutez le cacao, les graines de chia et l\'huile de coco</li><li>Mixez à nouveau jusqu\'à ce que tout soit bien mélangé</li><li>Formez des boules de la taille d\'une noix</li><li>Roulez-les dans la coco râpée</li><li>Conservez au réfrigérateur dans un contenant hermétique</li></ol>',
  '{"calories": 120, "protein": 4, "carbs": 18, "fat": 5}',
  false,
  true,
  NOW()
),
(
  'Buddha Bowl aux Légumes Croquants',
  'buddha-bowl-legumes-croquants',
  'Un bowl coloré et équilibré avec des légumes croquants, des protéines et une sauce crémeuse.',
  '/api/placeholder/400/300',
  '["/api/placeholder/400/300", "/api/placeholder/400/300", "/api/placeholder/400/300"]',
  'lunch',
  20,
  1,
  true,
  'easy',
  '["équilibré", "couleurs", "crudités", "vegan", "sans-gluten"]',
  '["100g de quinoa cuit", "1/2 avocat", "1 carotte râpée", "1/2 concombre en rondelles", "50g de chou rouge râpé", "2 cuillères à soupe de pois chiches", "1 cuillère à soupe de graines de tournesol", "Sauce tahini", "Jus de citron", "Sel et poivre"]',
  '<h3>Préparation</h3><ol><li>Préparez le quinoa selon les instructions</li><li>Coupez l\'avocat en tranches et le concombre en rondelles</li><li>Râpez la carotte et le chou rouge</li><li>Disposez tous les ingrédients dans un bol</li><li>Préparez la sauce en mélangeant tahini, jus de citron, sel et poivre</li><li>Arrosez le bowl de sauce et servez</li></ol>',
  '{"calories": 380, "protein": 14, "carbs": 48, "fat": 16}',
  true,
  true,
  NOW()
),
(
  'Pancakes Protéinés aux Flocons d\'Avoine',
  'pancakes-proteines-flocons-avoine',
  'Des pancakes moelleux et riches en protéines, parfaits pour un petit-déjeuner sportif.',
  '/api/placeholder/400/300',
  '["/api/placeholder/400/300", "/api/placeholder/400/300"]',
  'breakfast',
  20,
  2,
  true,
  'easy',
  '["protéines", "flocons d\'avoine", "sans-gluten", "vegan"]',
  '["100g de flocons d\'avoine", "1 banane mûre", "2 cuillères à soupe de poudre de protéines", "150ml de lait d\'amande", "1 cuillère à café de levure chimique", "1 cuillère à soupe de sirop d\'érable", "Huile de coco pour la cuisson"]',
  '<h3>Préparation</h3><ol><li>Mixez les flocons d\'avoine en farine</li><li>Écrasez la banane et mélangez avec le lait d\'amande</li><li>Ajoutez la farine d\'avoine, les protéines et la levure</li><li>Mélangez jusqu\'à obtenir une pâte homogène</li><li>Faites chauffer une poêle avec un peu d\'huile de coco</li><li>Versez des petites quantités de pâte et faites cuire 2-3 min de chaque côté</li><li>Servez avec du sirop d\'érable</li></ol>',
  '{"calories": 280, "protein": 20, "carbs": 35, "fat": 6}',
  false,
  true,
  NOW()
);

-- Vérification des insertions
SELECT 
  title, 
  category, 
  difficulty, 
  is_premium, 
  is_published,
  array_length(ingredients, 1) as nb_ingredients,
  array_length(tags, 1) as nb_tags
FROM recipes 
ORDER BY created_at DESC;
